import test from"node:test";import assert from"node:assert/strict";import fs from"node:fs";
import{LABC_FIXTURE}from"../public/manuscript-reconciliation-fixture.js";
import{READ_ONLY_ACTIONS,available,filterRows,mapCatalogPayload,normalizeWhitespace,preserveText}from"../public/manuscript-reconciliation.js";
test("LABC fixture reconciles verified totals",()=>{assert.equal(LABC_FIXTURE.rows.length,49);assert.equal(filterRows(LABC_FIXTURE.rows,{status:"auto_approved"}).length,24);assert.equal(filterRows(LABC_FIXTURE.rows,{status:"pending"}).length,25);assert.equal(LABC_FIXTURE.reconciliation.expectedResolvedCount,45);assert.equal(LABC_FIXTURE.reconciliation.preferredLegacySource.id,4);assert.deepEqual([LABC_FIXTURE.reconciliation.priorSource.id,LABC_FIXTURE.reconciliation.candidateSource.id],[7,8])});
test("bucket, status, and search filters work",()=>{assert.equal(filterRows(LABC_FIXTURE.rows,{bucket:"Auto-Approved"}).length,24);assert.equal(filterRows(LABC_FIXTURE.rows,{bucket:"Added",status:"pending"}).length,5);assert.equal(filterRows(LABC_FIXTURE.rows,{search:"Ya’arburnee"}).length,1);assert.equal(filterRows(LABC_FIXTURE.rows,{search:"no such poem"}).length,0)});
test("known PDF warnings are presented",()=>{for(const title of["Ya’arburnee","the pH balance of parenting yourself"]){const[row]=filterRows(LABC_FIXTURE.rows,{search:title});assert.ok(row.warnings.length);assert.ok(row.buckets.includes("Image-Backed or OCR Required"))}});
test("missing data is explicit and stanza blank lines survive",()=>{assert.equal(available(null),"Unavailable");assert.equal(preserveText("one\r\n\r\ntwo"),"one\n\ntwo");assert.equal(normalizeWhitespace("one  \n\n  two"),"one\n\n two")});
test("Catalog mapping rejects incomplete contracts and leaves unmapped rows unclassified",()=>{assert.throws(()=>mapCatalogPayload({},[]),/authoritative totals/);assert.deepEqual(mapCatalogPayload({totals:{resolutionRows:1}},[{status:"pending"}]).rows[0].buckets,["Unclassified"]);assert.deepEqual(mapCatalogPayload({totals:{resolutionRows:1}},[{buckets:["Added"]}]).rows[0].buckets,["Added"])});
test("Phase 1 exposes no mutations and includes error, empty, and narrow states",()=>{assert.deepEqual(READ_ONLY_ACTIONS,[]);const html=fs.readFileSync(new URL("../public/manuscript-reconciliation.html",import.meta.url),"utf8");const app=fs.readFileSync(new URL("../public/manuscript-reconciliation.js",import.meta.url),"utf8");assert.match(html,/@media\(max-width:900px\)/);assert.match(app,/demo\"\)===\"error/);assert.match(app,/demo\"\)===\"empty/);assert.doesNotMatch(app,/method:\"(?:POST|PUT|PATCH|DELETE)/)});
