import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import {READ_ONLY_ACTIONS,RECONCILIATION_API,available,boot,filterRows,isTeamProfile,mapCatalogPayload,mapFixturePayload,normalizeWhitespace,preserveText} from "../public/manuscript-reconciliation.js";
const rows=[{identity:"Alpha",status:"auto_approved",buckets:["Auto-Approved"],warnings:[]},{identity:"Beta",status:"pending",buckets:["Unclassified"],warnings:["Visual review required"]}];
const syntheticCatalogProxy={fixtureMode:false,readOnly:true,dataSource:{type:"live_catalog_api",liveCatalogIntegration:true},reconciliation:{id:2,bookTitle:"Synthetic Book",author:null,expectedResolvedCount:1,totals:{resolutionRows:1,autoApproved:0,pending:1,blockedOrWarning:0},preferredLegacySource:{id:4},priorSource:{id:7},candidateSource:{id:8,parserWarnings:[]},contractGaps:["Synthetic contract gap"]},rows:[{resolutionId:1,identity:"Synthetic row",status:"pending",buckets:["Unclassified"],prior:{text:"prior"},candidate:{text:"candidate"},warnings:[]}],contractGaps:["Synthetic contract gap"]};
const syntheticFixture={...syntheticCatalogProxy,fixtureMode:true,fixtureLabel:"Fixture-backed · not live Catalog API integration",dataSource:{type:"deterministic_fixture",liveCatalogIntegration:false}};
test("team access accepts only established roles-array conventions",()=>{assert.equal(isTeamProfile({roles:["team"]}),true);assert.equal(isTeamProfile({roles:["admin"]}),true);assert.equal(isTeamProfile({roles:["user"]}),false);assert.equal(isTeamProfile({role:"admin"}),false);assert.equal(isTeamProfile(null),false)});
test("bucket, status, and search filters work without inference",()=>{assert.equal(filterRows(rows,{bucket:"Auto-Approved"}).length,1);assert.equal(filterRows(rows,{status:"pending"}).length,1);assert.equal(filterRows(rows,{search:"visual"}).length,1);assert.equal(filterRows(rows,{search:"missing"}).length,0)});
test("missing data is explicit and stanza blank lines survive",()=>{assert.equal(available(null),"Unavailable");assert.equal(preserveText("one\r\n\r\ntwo"),"one\n\ntwo");assert.equal(normalizeWhitespace("one  \n\n  two"),"one\n\n two")});
test("Catalog mapping rejects incomplete contracts and leaves unmapped rows unclassified",()=>{assert.throws(()=>mapCatalogPayload({},[]),/authoritative totals/);assert.deepEqual(mapCatalogPayload({totals:{resolutionRows:1,autoApproved:0,pending:1}},[{status:"pending"}]).rows[0].buckets,["Unclassified"]);assert.deepEqual(mapCatalogPayload({totals:{resolutionRows:1,autoApproved:0,pending:0}},[{buckets:["Added"]}]).rows[0].buckets,["Added"]);assert.throws(()=>mapCatalogPayload({totals:{resolutionRows:1,autoApproved:1,pending:0}},[{status:"pending"}]),/status totals/)});
test("fixture mapping enforces read-only mode and reconciled status totals",()=>{assert.equal(mapFixturePayload(syntheticFixture).fixtureMode,true);assert.throws(()=>mapFixturePayload({...syntheticFixture,readOnly:false}),/read-only/);assert.throws(()=>mapFixturePayload({...syntheticFixture,reconciliation:{...syntheticFixture.reconciliation,totals:{resolutionRows:2,autoApproved:0,pending:1}}}),/row totals/);assert.throws(()=>mapFixturePayload({...syntheticFixture,reconciliation:{...syntheticFixture.reconciliation,totals:{resolutionRows:1,autoApproved:1,pending:0}}}),/status totals/)});
test("server proxy uses the protected Catalog read contracts",()=>{const server=fs.readFileSync(new URL("./index.js",import.meta.url),"utf8");assert.match(server,/CATALOG_RECONCILIATION_API_KEY/);assert.ok(server.includes("/reconciliations/${encodedId}"));assert.ok(server.includes("/reconciliations/${encodedId}/resolutions"));assert.match(server,/live_catalog_api/);assert.match(server,/liveCatalogIntegration: true/);assert.match(server,/const CATALOG_RECONCILIATION_PREVIEW_API = CANONICAL_CATALOG_API/);assert.doesNotMatch(server,/button-poetry-catalog-reconciliation-preview/);assert.doesNotMatch(server,/handleManuscriptReconciliationFixture/)});
test("public assets contain no reconciliation fixture and every demo path follows authorization",()=>{const app=fs.readFileSync(new URL("../public/manuscript-reconciliation.js",import.meta.url),"utf8");assert.doesNotMatch(app,/labc-source-7-to-8|source_registry\.db|1sJNtIpkvH7Vihd-M8_S1k_ELXjmtsCEG/);assert.equal(fs.existsSync(new URL("../public/manuscript-reconciliation-fixture.js",import.meta.url)),false);const authIndex=app.indexOf("await authorizeTeam()");const paramsIndex=app.indexOf("new URLSearchParams(location.search)");assert.ok(authIndex>=0);assert.ok(paramsIndex>authIndex);assert.match(app,/Array\.isArray\(profile\?\.roles\)/)});
test("Phase 1 exposes no mutation actions and the shell is desktop-first",()=>{assert.deepEqual(READ_ONLY_ACTIONS,[]);const html=fs.readFileSync(new URL("../public/manuscript-reconciliation.html",import.meta.url),"utf8");const app=fs.readFileSync(new URL("../public/manuscript-reconciliation.js",import.meta.url),"utf8");assert.match(html,/Checking authenticated team access/);assert.match(app,/Desktop-first review workspace/);assert.match(app,/Live Catalog integration/);assert.doesNotMatch(app,/method:"(?:POST|PUT|PATCH|DELETE)/)});
function installClientGlobals({user,profile}){const previous={document:globalThis.document,firebase:globalThis.firebase,fetch:globalThis.fetch,location:globalThis.location};const calls=[];const root={innerHTML:"Checking authenticated team access",querySelector:()=>null,querySelectorAll:()=>[]};globalThis.document={querySelector:()=>root};globalThis.location={search:""};globalThis.firebase={apps:[],initializeApp:()=>({}),auth:()=>({onAuthStateChanged:resolve=>resolve(user)})};globalThis.fetch=async(url,options={})=>{calls.push({url,authorization:options.headers?.Authorization||""});if(url==="/api/me")return{ok:true,json:async()=>profile};if(url===RECONCILIATION_API)return{ok:true,json:async()=>syntheticCatalogProxy};throw Error("Unexpected request: "+url)};return{root,calls,restore(){for(const[key,value]of Object.entries(previous))value===undefined?delete globalThis[key]:globalThis[key]=value}}}
test("client renders no reconciliation data and makes no request before auth resolves",async()=>{const previous={document:globalThis.document,firebase:globalThis.firebase,fetch:globalThis.fetch,location:globalThis.location};const calls=[];const root={innerHTML:"Checking authenticated team access",querySelector:()=>null,querySelectorAll:()=>[]};let resolveAuth;globalThis.document={querySelector:()=>root};globalThis.location={search:""};globalThis.firebase={apps:[],initializeApp:()=>({}),auth:()=>({onAuthStateChanged:resolve=>{resolveAuth=resolve}})};globalThis.fetch=async url=>{calls.push(url);throw Error("Request before authorization: "+url)};try{const pending=boot();await Promise.resolve();assert.equal(root.innerHTML,"Checking authenticated team access");assert.deepEqual(calls,[]);resolveAuth(null);await pending;assert.match(root.innerHTML,/Team access required/);assert.doesNotMatch(root.innerHTML,/Authenticated team access|Synthetic Book/)}finally{for(const[key,value]of Object.entries(previous))value===undefined?delete globalThis[key]:globalThis[key]=value}});
test("client denies a synthetic non-team profile before fixture reads",async()=>{const env=installClientGlobals({user:{getIdToken:async()=>"synthetic-user-token"},profile:{roles:["user"]}});try{await boot();assert.deepEqual(env.calls,[{url:"/api/me",authorization:"Bearer synthetic-user-token"}]);assert.match(env.root.innerHTML,/Team access required/);assert.doesNotMatch(env.root.innerHTML,/Authenticated team access|Synthetic Book/)}finally{env.restore()}});
test("client starts the live Catalog proxy read only after synthetic team or admin authorization",async()=>{for(const role of["team","admin"]){const token=`synthetic-${role}-token`;const env=installClientGlobals({user:{getIdToken:async()=>token},profile:{roles:[role]}});try{await boot();assert.deepEqual(env.calls,[{url:"/api/me",authorization:`Bearer ${token}`},{url:RECONCILIATION_API,authorization:`Bearer ${token}`}]);assert.match(env.root.innerHTML,/Authenticated team access/);assert.doesNotMatch(env.root.innerHTML,/Fixture-backed/);assert.match(env.root.innerHTML,/Live Catalog integration: yes/);assert.match(env.root.innerHTML,/Synthetic Book/)}finally{env.restore()}}});

test("reconciliation auth config matches Poetry Please Admin",()=>{const admin=fs.readFileSync(new URL("../public/admin.html",import.meta.url),"utf8");const app=fs.readFileSync(new URL("../public/manuscript-reconciliation.js",import.meta.url),"utf8");const value=(source,key)=>source.split(key)[1]?.split('"')[1];for(const key of["apiKey","authDomain","projectId","appId"])assert.equal(value(app,key),value(admin,key),key+" must match Admin authentication")});
