import test from"node:test";import assert from"node:assert/strict";import fs from"node:fs";
import{READ_ONLY_ACTIONS,available,filterRows,isTeamProfile,mapCatalogPayload,normalizeWhitespace,preserveText}from"../public/manuscript-reconciliation.js";
const rows=[{identity:"Alpha",status:"auto_approved",buckets:["Auto-Approved"],warnings:[]},{identity:"Beta",status:"pending",buckets:["Unclassified"],warnings:["Visual review required"]}];
test("team access accepts only established roles-array conventions",()=>{assert.equal(isTeamProfile({roles:["team"]}),true);assert.equal(isTeamProfile({roles:["admin"]}),true);assert.equal(isTeamProfile({roles:["user"]}),false);assert.equal(isTeamProfile({role:"admin"}),false);assert.equal(isTeamProfile(null),false)});
test("bucket, status, and search filters work without inference",()=>{assert.equal(filterRows(rows,{bucket:"Auto-Approved"}).length,1);assert.equal(filterRows(rows,{status:"pending"}).length,1);assert.equal(filterRows(rows,{search:"visual"}).length,1);assert.equal(filterRows(rows,{search:"missing"}).length,0)});
test("missing data is explicit and stanza blank lines survive",()=>{assert.equal(available(null),"Unavailable");assert.equal(preserveText("one\r\n\r\ntwo"),"one\n\ntwo");assert.equal(normalizeWhitespace("one  \n\n  two"),"one\n\n two")});
test("Catalog mapping rejects incomplete contracts and leaves unmapped rows unclassified",()=>{assert.throws(()=>mapCatalogPayload({},[]),/authoritative totals/);assert.deepEqual(mapCatalogPayload({totals:{resolutionRows:1}},[{status:"pending"}]).rows[0].buckets,["Unclassified"]);assert.deepEqual(mapCatalogPayload({totals:{resolutionRows:1}},[{buckets:["Added"]}]).rows[0].buckets,["Added"])});
test("public assets contain no reconciliation fixture and every demo path follows authorization",()=>{const app=fs.readFileSync(new URL("../public/manuscript-reconciliation.js",import.meta.url),"utf8");assert.doesNotMatch(app,/manuscript-reconciliation-fixture|LABC_FIXTURE|fixture=1/);assert.equal(fs.existsSync(new URL("../public/manuscript-reconciliation-fixture.js",import.meta.url)),false);const authIndex=app.indexOf("await authorizeTeam()");const paramsIndex=app.indexOf("new URLSearchParams(location.search)");assert.ok(authIndex>=0);assert.ok(paramsIndex>authIndex);assert.match(app,/Array\.isArray\(profile\?\.roles\)/)});
test("Phase 1 exposes no mutation actions and the shell is desktop-first",()=>{assert.deepEqual(READ_ONLY_ACTIONS,[]);const html=fs.readFileSync(new URL("../public/manuscript-reconciliation.html",import.meta.url),"utf8");const app=fs.readFileSync(new URL("../public/manuscript-reconciliation.js",import.meta.url),"utf8");assert.match(html,/Checking authenticated team access/);assert.match(app,/Desktop-first review workspace/);assert.doesNotMatch(app,/method:"(?:POST|PUT|PATCH|DELETE)/)});
