name: Deploy to Firebase Hosting and Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Functions dependencies
        run: |
          cd functions
          npm install

      - name: Deploy Hosting and Functions
        uses: Firebase/firebase-actions@v1
        with:
          credentials: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: 'poetry-please'
          channelId: 'live'
          deployTargets: 'hosting,functions'
